### ISSUE TITLE
[SALTSTACK] - Update SHA256 hash for "Volatility-Cheatsheet.pdf"

### ISSUE THREAD

**Issue by ch40s** [sans-dfir/sift#203]
Please update the SHA256 hash for Volatility-Cheatsheet.pdf because the installation and upgrade commands currently fail.

The current hash for the file "https://digital-forensics.sans.org/media/volatility-memory-forensics-cheat-sheet.pdf" is "699ea76d1713074fe0d32eaad437f3b2c7e089ae8d00e5d43aa97cc81ed0f44f" and not "425aa18a8490f8eaa065a9507ba5f4e78eafe8a02c5bfdd41b6fce4cc43b52c2".

https://github.com/sans-dfir/sift-saltstack/blob/a85d5a59c5ea61c29a8f1df20c5f92718feac28b/sift/config/user/pdfs.sls : 

```
sift-pdf-cheatsheet-volatility:
 file.managed:
   - name: /home/{{ user }}/Desktop/Volatility-Cheatsheet.pdf
   - source: https://digital-forensics.sans.org/media/volatility-memory-forensics-cheat-sheet.pdf
   - source_hash: sha256=425aa18a8490f8eaa065a9507ba5f4e78eafe8a02c5bfdd41b6fce4cc43b52c2
   - user: {{ user }}
   - group: {{ user }}
   - require:
   - user: sift-user-{{ user }}
```
